[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/'
extend-exclude = '\.ipynb_checkpoints'

[tool.isort]
profile = "black"
line_length = 88
force_sort_within_sections = true
known_first_party = ["alphamind"]

[tool.flake8]
max-line-length = 88
extend-ignore = E203
exclude = "venv,.git,__pycache__,docs/source/conf.py,old,build,dist"
per-file-ignores =
    __init__.py:F401

[tool.pylint.MASTER]
extension-pkg-whitelist = tensorflow.keras
